#!/bin/sh

# Testing
service hostapd stop
service dnsmasq stop

#################################################
############ SET UP THE NETWORK #################
#################################################

############## MOVE FILE LOCATIONS ##############
echo "Moving files"
./mv-files

############### INTERFACE DECLARATIONS ##########

INGRESS=wlan0
EGRESS=eth0

################# START WIFI ####################

if [ -z "$(ps -e | grep wlan0)" ]
then
  echo "Killing WiFi"
  ifconfig $INGRESS down
  sleep 1s
fi

echo "Starting wifi"
ifconfig wlan0 up 10.0.0.1 netmask 255.255.255.0
sleep 2s

#################################################
################ IPTABLES SETUP #################
#################################################

iptables --flush
iptables --table nat --flush
iptables --delete-chain
iptables --table nat --delete-chain
iptables --table nat --append POSTROUTING --out-interface eth0 -j MASQUERADE
iptables --append FORWARD --in-interface wlan0 -j ACCEPT

############## FORWARD IP TRAFFIC ###############

sysctl -w net.ipv4.ip_forward=1

################ START SERVICES #################

service dnsmasq start
service hostapd start

